/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritanc;


public class Library {
    public static void main(String[] args){
        Restaurant mcDonalds = new Restaurant("mcDonalds",3,"$");
        Review comments = new Review("amazing" , "abdallah" ,3);
        System.out.println(comments.toString());

        mcDonalds.addReview(comments);
        System.out.println(mcDonalds.toString());

        System.out.println(mcDonalds.toString());
    }
}
