/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritanc;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;

class LibraryTest {
    @Test void testResToString() {
        Restaurant r1 = new Restaurant("mac",5,"$$");
        System.out.println(r1.toString());
        String note = r1.toString();
        assertEquals(" Resturant mac start 5 price category $$ []",note);
    }


    @Test void testReviewToString() {
        Review rev1 = new Review("bad","Abdallah",2);
        String note = rev1.toString();
        assertEquals(" comments : bad /  name : Abdallah start * 2",note);



    }
    @Test void testAddReview(){
        Restaurant r1 = new Restaurant("mac",0,"low");
        Review rev1 = new Review("bad","Abdallah",2);
        Review rev2 = new Review("well","ahmad",3);

        r1.addReview(rev1);
        r1.addReview(rev2);
        String note =r1.toString();
        assertEquals(" Resturant mac start 1 price category low [ comments : bad /  name : Abdallah start * 2,  comments : well /  name : ahmad start * 3]",note);

    }


    @Test void testShop(){
        Shop place = new Shop("gichi","$$$");


//        place.addReview("good","abdallah",4);
        String note = place.toString();
        System.out.println(note);

        assertEquals("Shop: gichi  Rate depend on reviews = 0  price category: $$$ ",note);
    }

    @Test void testTheater(){

        ArrayList<String> passingThis =  new ArrayList<>();
        Theater place = new Theater("abdallah",passingThis);
        place.addMovie("movie1");
        place.addMovie("movie2");

        place.addReview("good","abdallah",4,"wow");
        String note = place.toString();


        assertEquals("Theater{name='abdallah', reviewList=[ comments : good /  name : abdallah start * 4], movieList=[movie1, movie2]}",note);


        place.removeMovie("movie2");
        String note2 = place.toString();


        assertEquals("Theater{name='abdallah', reviewList=[ comments : good /  name : abdallah start * 4], movieList=[movie1]}",note2);

    }

}
