/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.io.ByteArrayOutputStream;
import java.util.ArrayList;
import java.io.PrintStream;

class LibraryTest {
    // @Test void someLibraryMethodReturnsTrue() {
    //     Library classUnderTest = new Library();
    //     assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    // }

    @Test public void testRoll() {
        int [] rollResult = Library.roll(5);
        assertEquals( 5, rollResult.length);
    }

    @Test public void testContainsDuplicates() {
        int [] array ={1,2,5,4,5,9,8,2,10};
        assertTrue(Library.containsDuplicates(array));
    }

    @Test public void testCalcAverage() {
        int [] array ={65, 56, 55, 52, 55, 62, 57};
        assertTrue(Library.calculatingAverages(array) ==57.0);
    }

    @Test public void testArrayOfArrays() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        int [] array = weeklyMonthTemperatures[2];
        int [] newArr = Library.arrayOfArrays(weeklyMonthTemperatures);
        assertArrayEquals(array, newArr);
    }


    @Test public void testAnalysisWeatherData() throws Exception {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();

        System.setOut(new PrintStream(outContent));
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        Library.analysisWeatherData(weeklyMonthTemperatures);

        String expectedOutput  = "High: 72\n" +
                "Low: 51\n" +
                "Never saw temperature: 63\n" +
                "Never saw temperature: 67\n" +
                "Never saw temperature: 68\n" +
                "Never saw temperature: 69\n";

        assertEquals(expectedOutput,outContent.toString());
    }

    @Test public void testTally(){
        ArrayList<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        assertEquals("Bush",Library.tally(votes),"the winner is bush");

    }
}

