/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.ArrayList;

class LibraryTest {

    @Test
    public  void testroll() {
        int rollsNumber = 4;
        assertEquals(rollsNumber,Library.roll(rollsNumber).size());
    }
    @Test
    public void averageTest() {
        assertEquals(2.6, Library.calculatingAverages(new int[] {1,2,6,3,1}));
    }

    @Test
    public void containsDuplicates() {
        assertTrue(Library.containsDuplicates(new int[] {1,2,6,3,1}));
    }
    @Test
    public void lowestAverage() {

        assertArrayEquals(new int[] {55, 54, 60, 53, 59, 57, 61},
                Library.lowestAverage(new int[][] {
                        {66, 64, 58, 65, 71, 57, 60},
                        {57, 65, 65, 70, 72, 65, 51},
                        {55, 54, 60, 53, 59, 57, 61},
                        {65, 56, 55, 52, 55, 62, 57}
                }));
    }
    @Test
    public void analyzingWeather(){
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        String value = "\nNever saw temperature: 63" +
                "\nNever saw temperature: 67" +
                "\nNever saw temperature: 68" +
                "\nNever saw temperature: 69";
        assertEquals(value,Library.analysisWeatherData(weeklyMonthTemperatures));
    }
    @Test
    public void tally(){
        ArrayList<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        assertEquals("Bush",Library.tally(votes));

    }
}