/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public static void main(String[] args){
        Restaurant mcDonalds = new Restaurant("mcDonalds",3,2);
        Review comments = new Review("amazing","abdallah",3);
        System.out.println(comments.toString());

        mcDonalds.addReview("this is amazing","abdallah",3);
        System.out.println(mcDonalds.toString());
        mcDonalds.addReview("yum yum","dima",2);
        System.out.println(mcDonalds.toString());
        System.out.println();
    }
}
